#!/bin/bash

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
VENV_DIR="$SCRIPT_DIR/fprime-venv"

if [[ -d "$VENV_DIR" && "${VIRTUAL_ENV:-}" != "$VENV_DIR" ]]; then
	# shellcheck disable=SC1091
	source "$VENV_DIR/bin/activate"
fi

rm -r build
make SIMULATION=native prep
./do
