#!/bin/bash

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
VENV_DIR="$SCRIPT_DIR/fprime-venv"

if [[ -d "$VENV_DIR" && "${VIRTUAL_ENV:-}" != "$VENV_DIR" ]]; then
	# shellcheck disable=SC1091
	source "$VENV_DIR/bin/activate"
fi
${SCRIPT_DIR}/do || exit 1
cd build/exe/cpu1/
./core-cpu1
